- hosts: web
  become: yes

  vars:
    image_tag: latest

  tasks:

    - name: Run FastAPI container
      docker_container:
        name: fastapi-app
        image: "james2835/fastapi-app:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
