- hosts: web
  become: yes

  tasks:

    - name: Wait for cloud-init to finish
      shell: cloud-init status --wait

    - name: Update packages
      yum:
        name: "*"
        state: latest

    - name: Install required system packages
      yum:
        name:
          - docker
          - python3
          - python3-pip
        state: present

    - name: Install compatible Python Docker SDK and dependencies
      pip:
        name:
          - "docker<6"
          - "requests<2.32"
          - "urllib3<2"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Restart Docker to apply changes
      service:
        name: docker
        state: restarted
